service: product-service
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  getProductsList:
    handler: handlers/products-list.getProductsList
    events:
      - httpApi:
          method: get
          path: /products
          cors: true
  
  getProductsById:
    handler: handlers/products.getProductsById
    events:
      - httpApi:
          method: get
          path: /products/{productId}
          cors: true
