service: import-service
frameworkVersion: '2'
useDotenv: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
    authorizers:
      basicAuthorizer:
        functionArn: ${env:BASIC_AUTHORIZER}
        resultTtlInSeconds: 0
        identitySource: $request.header.Authorization
        type: request

  environment:
    SQS_URL: ${env:SQS_URL}

  iamRoleStatements:
    - Effect: Allow
      Action: s3:ListBucket
      Resource:
        - arn:aws:s3:::rsschool-imported-products
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::rsschool-imported-products/*
    - Effect: Allow
      Action: sqs:*
      Resource:
        - ${env:PRODUCTS_QUEUE}

functions:
  importProductsFile:
    handler: handlers/file-uploader.importProductsFile
    events:
      - httpApi:
          method: get
          path: /import
          authorizer:
            name: basicAuthorizer
            
  importFileParser:
    handler: handlers/file-parser.importFileParser
    events:
      - s3:
          bucket: rsschool-imported-products
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
