service: import-service
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::rsschool-imported-products'
    - Effect: 'Allow'
      Action: 's3:*'
      Resource:
        - 'arn:aws:s3:::rsschool-imported-products/*'

functions:
  importProductsFile:
    handler: handlers/file-uploader.importProductsFile
    events:
      - httpApi:
          method: get
          path: /import
